apiVersion: v1
kind: Service
metadata:
  name: websocket-playground-service
spec:
  type: NodePort
  selector:
    app: websocket-playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
