apiVersion: v1
kind: Service
metadata:
  name: websocket-playground-ws-service
spec:
  type: NodePort
  selector:
    app: websocket-playground-ws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-playground-uws-service
spec:
  type: NodePort
  selector:
    app: websocket-playground-uws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
